kind: ENC[AES256_GCM,data:jqMkspSc,iv:XggcrpacCLiq/hzn5LAQZ0YIeDWv5j822E8pbnzfXTs=,tag:xfuglD3DpXXjM2uMLNM2Dg==,type:str]
ansible_user: ENC[AES256_GCM,data:PPudnKJG,iv:klxwJu5yZSNIvPuD3W1gohHkLcQcELGhAI/SVe+i6qU=,tag:brtNbaurWpekqgs+Nt9FKQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jJ5Y+mDbDb4=,iv:P59Oz4zaJDGzjbHiAvtzm8U7tVsHeWlkiC30I9/nTrw=,tag:ASTbtd280r3AKmA6Rpv9cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkekpNdnhnUWhWWkhTNEVR
            R1BYZUZuOTIzNXdxOEpkQUd2ZVdhNGtWdkU4Cldxd3MvWG1UM3pUUTFsZ0tzWjdq
            Q2lPSkt3VmNvZTYzM2hCekJCeGZ2NlEKLS0tIExZejBGSlAzNER4NThXWjF3RzFp
            R3ZiY2sxdjVqZkppcHN4ZlBqN1dScTAK9JnpMKpGvfd9dL5c7hCAz0lF1eQtwHIE
            k7I+kfazQ4fNPWXcH2WjiFoHjbnWBnZuWRqMnyxLcV3M8mRYSdgAew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T09:24:38Z"
    mac: ENC[AES256_GCM,data:qYFf+1eo/L9kKlK3aXhTEgnvk6STV4pWj63mxvoxLKFArqzGuFkMwJONYvHEhr1IR2lfamzv3sW4kEmf4+OJq8+x9MKpz8u0AwgvRS7v0TepdfIjQFP6r2PqVdqERV3KWTVZzJKn2lTNGpeGonP9W/kysb4oFCMKSeVZU+zwjck=,iv:dI6WNEVNDKJm4yTPkztvA9/PrrAJ9sAknYErVsGo7UQ=,tag:THia494VvxuXRn9nkfJqJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
