apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:LB+ebxk=,iv:AXlfUgXQ9IQAL5RRItPVYCM7pbbxAuVip0LinGW+smc=,tag:dG/whRQ3WjNNjmgDd5DOzg==,type:str]
    admin-password: ENC[AES256_GCM,data:e7zoqXAV7PDC2/Vg/nabFumL7VmKJKZ/,iv:AdRkyn7G/u65rdY3dnQDKtxD8+JA/3keHh88UpGVNo4=,tag:XTYE6DG/mS/GTgdDK/XYqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTnFuSGU3Q0Q3WGtDcnNY
            T0R6eFZyN0s1K2ROMXJxZ2E3Um5MSzFvcW1JCklBZ1FHY1Y1Y3hUT2cvNHBrbkJG
            d2hCS3hSSzZ0WVNWSkZOOHRJTW8yYVEKLS0tIG93Uk1zUWp1OFZkTEtUSW52YWNn
            WjFDTUsrT3VqVFIvWU9sNi9mV2tLak0KPLnVCK7q1sekU2UAsOAF+ehh5tzPvXdx
            inY0QSHWIEXIWX4zIzrW0AXQCnFNHwxwvavFZrTEwcP5Na66cyiPmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T11:42:45Z"
    mac: ENC[AES256_GCM,data:rMNPQDVAVhrOu5eUvzUbKFWi+doNQPOafi18BZOus1QYm4U1LOlDdhZNIrKxI/+Oaptez/z55pe4CAEy/U9ZCf0U5NLtkl/G2vd6+S3mscigIbQULfNwpvSxT4ue978hxMYN1EKbZ0OSeCS4IZX4rAzyrs9+L6fmwPGSsn0m3p0=,iv:CMl3IQVRpcVro+ZeeBDP3lw8YTtYPLnXn05oqT0vSh0=,tag:e1TJ5LqWKI6M0e4fmElKLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
