apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:PCA762s=,iv:zWaha0XkDazs5WoxYUONXR7BeoYGXp8Pmck3DrfM9KQ=,tag:hup5q19kb5dfH4/8dTyDkQ==,type:str]
    admin-password: ENC[AES256_GCM,data:V4aRgKAo+u1rqDpheaHLmeR9HrLtIZXV,iv:mmdOVIavrivHQtd1Ali3KyxAVqll2NFNe2wpg5GE6kc=,tag:Hw2eE6WA2QoBe6VGrrOVkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWkxUT3RKQWhEWlFyd2FF
            bG1IdHJURERLVFRLM3JBNDJOTGZ0MW9xTmxrCmx3cFdHWkVtSkxtQlNBaHFCeUhC
            anJuSlRNQzIxU3pZOGtRUDU2NE1iVjAKLS0tIElDL0V1MHBkbVRGbmVQL25lSmlQ
            aWM3OG9iekNLSmM1SmZMWUNqSWZPalUKO0DguOzXOa5vP9eU7kCWCdKbPzzGjlM/
            7j1ZTqwTOk46/fOeWdvkml6fS2j1hjgbudb4la+T9BAtuyBOwHANIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T09:24:39Z"
    mac: ENC[AES256_GCM,data:PDqKhpdTPxNXnywrFD1Noq49/lEAuHwWlUHCty5iS6eyJyzoVHXMmDa7Ugs5FsFTNfGtlzxNjIdjsOoIa9CmkKNnTUHbPYwg5mDwqyi2cVkQjWnkDZV+NivAkYhS46zoeyQm90Ed+Zbl10vFn1ji8zhpi3aqEtl8isSk2y1hVrg=,iv:L+WT9svwlQ90c7fHjyXbHhabc2JsKmT+dWtPz+JEH+0=,tag:9L5UOreAIOZcKvcoopsRKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
