apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:G7hv4+bbVlrsjQDgauZBloyxKaKQvK+d,iv:Q7NVNp+NXPJjnX1WDNe3dOxVfiZuyP38jc6NqoccCuk=,tag:C6kyMsC2VRMSyGq+PV6LkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSG5kb1puaXVCQUd2RmEr
            ZDJnYmFtWTdnWVM0VGlYUHU2Mk52ZEpCdUJnCmRPdWIrcHBSN0hGUlNlSC9tYmJW
            Rjd0SHhYUEpqVm42Skx6ZGQ4blpBZkkKLS0tIHQxNFNTRlptUE9WaW9FY0RVV3dm
            UVRWYlpHV1JsNUlqeFc4Zk9JUE9mUEkK4rAWPx36h5mRJjLyRXSEJw3i814y+86g
            I5U8YQgNuBIWPR0fdxxrTbqMDCaESZ/mGlOxFL167FsirLTYXtHp9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T11:42:44Z"
    mac: ENC[AES256_GCM,data:zOnIlFWbBpiulqz0/xYQvImr1+Ab1iad8xp1eHXZPvfm90hZI6ojz0ZIKyJNTqP7MnfJCYulrRG824TMnE5cmXtji4YEiqK5RX7wgVTAvOcol11LHh25h2UyI3wJhDPMYOA/UtkHyhbqxIsvu67F7eriMyb/YTb9TaqT6VRNLP8=,iv:IoQsNjmar+TUJXF3SQSYE+q2a8FFQcQczCGSbhZZQjI=,tag:6kciXFGgsoDB+kzv0g7eTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
