apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:wmCIWIRcT1SbUn9C1XtOyswGQIK8bh+YRwQZkxL/szRh9CaXIgTQ9w==,iv:8xgFUr+BD5xek7pWYFMjJ1Cea6YEYip3DNg7qIXBjGk=,tag:KTK/6Jpm35O6J9beXw6Nrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd0o0VjF5bVJEQnVkdWtp
            UVhRWnZVc2IvOXdPNnY1ZVgxTGpGbmpzL0VVCjdZVVJKZERrcDUxcStJVWVHSG5M
            ZHZ5UERPU1d0VEtNaGFiYUpmWkJabzgKLS0tIE5xWjk0NnV4c2U5SWZ6N2JQWTRi
            aDFYZVg2OTJxSjluK0d3RDh1SCs5Yk0KbUi7LTPtPtGc0V2JtsHnob3PEsgOhLw6
            4D3QtHuGF25xKRWdzWW53URbrbCKA41DVmUo9/izoxYhBcYFGv45TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T11:42:44Z"
    mac: ENC[AES256_GCM,data:AFf4kFelI/z1+Zrh6Wx27UvYghX+FiJkT00xXm0cM4onG2r0/ajHmV3kRKVGpotmhHfJN37lot3emEmGmuQI3NFkaZfIhPFyeLEm5Vb29fPmPCdsUtw9KgMoAU+ZX0R8KYihWEkbpLxVvSyYzjNIbvUJ38J8ilu1c5sW6gAy7HU=,iv:04xGY4i/A9SB+Dc2f03M9Zvpfne7N18vC8c2CqyuBO8=,tag:J4F48TVxXps+D344XAGQ4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
