---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk
  namespace: monitoring
spec:
  version: 8.12.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elk
  namespace: monitoring
  labels:
    app: elk
spec:
  version: 8.12.1
  count: 1
  elasticsearchRef:
    name: elk
