apiVersion: v1
data:
    dopplerToken: ENC[AES256_GCM,data:5MahKfvxsM81Sj/Df0RrA2AHzcwjvjPoyoffLdgq7w5l0z+PdvRZz72Bw9ciCnJlpsiftnjs2MRk7c8Zl6MVj2ATf+lb+XEi,iv:8KrxoOqqkoEcdtuh5Kc9JhKYyUB4F7oGJv6y2AtvZF8=,tag:VQYUsxCLNsZ65Qn4vK7RXQ==,type:str]
kind: Secret
metadata:
    name: doppler-token-auth-api
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kdf8mnyhpf45kv27a64h08e750st7qvr00xkvte58px68s73v8syaxk7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YnV5aXRxUnFseU54V2l3
            KzlscjNWbXJvTHJEZ0lQMm1yelJWMm85ekhjCkhjVEVJb3FUemp0NHdRbm9TSVFt
            Snp4ajczc3RhVVhMSU9ocVVOU3hCTHcKLS0tIHRuMVJSazd0RkcxTWdLS1kwUzlH
            UWFmN2FUT2kvYzdxSXJTcU1EZ2Q1b0UKz/lrXEKwkkrGX9xdwjKfbUB3zqLs6GPx
            fv11L79FTxO6h2RvakwQwf1iTp+itgddztcDyVwMilFJLgmMHirlJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T17:46:02Z"
    mac: ENC[AES256_GCM,data:9nTzV5yaOzSd1/f6wiLO9QO2DFlwyPFvN2XMqPxnMt24cHEf7NFmJ77Iz6F8aWu7PCeFRY68Ku6JsoUtM5IYihBDM8Khv23TVn5/G0DpbkuebLdPiuYwS0QqJJZZDFyz8h3ZT64p5ZAsfbWfyzn019j8oRy5X4IwVOW566GlkxU=,iv:Hp9feitZHMwnDYNzfeCP8eQ+16gVHJdNTGunE68Aubg=,tag:sf/bbouxP79soI6liiZI/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
