---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-test
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: doppler-test
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        testing_string: "{{ .TESTING__DOPPLER }}"

  dataFrom:
    - find:
        path: TESTING__
