---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: default
spec:
  chart:
    spec:
      chart: forecastle
      version: 1.0.127
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  interval: 1m0s
  releaseName: forecastle
  targetNamespace: default
  values:
    forecastle:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "forecastle.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
