---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: redis
  targetNamespace: default
  values:
    redis:
      auth:
        enabled: false
        sentinel: false
      master:
        persistence:
          enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 1m
      networkPolicy:
        enabled: false
      replica:
        persistence:
          enabled: false
      sentinel:
        enabled: true
        getMasterTimeout: 10
        masterSet: redis-master
        persistence:
          enabled: false
        startupProbe:
          failureThreshold: 2
